/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import static presentacion.ProyectoProgra.inscripcion1; // Por medio de este import, utilizaremos el objeto "inscripcion1" en esta otra ventana de JFrame

/**
 *
 * @author ronal
 */
public class jFrmPrincipal extends javax.swing.JFrame {

    //Inscripcion inscripcion1 = new Inscripcion();
    
    public jFrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtEquipos = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxtRegistroCompetidores = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jBtnRegistroCompetidores = new javax.swing.JButton();
        jBtnAsignarEquipos = new javax.swing.JButton();
        jBtnReiniciarSimulador = new javax.swing.JButton();
        jBtnCompetencias = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();
        jCboOrdenamiento = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTxtEquipos.setColumns(20);
        jTxtEquipos.setRows(5);
        jScrollPane1.setViewportView(jTxtEquipos);

        jTxtRegistroCompetidores.setColumns(20);
        jTxtRegistroCompetidores.setRows(5);
        jScrollPane2.setViewportView(jTxtRegistroCompetidores);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("REGISTRO DE COMPETIDORES");

        jBtnRegistroCompetidores.setText("Registro de Competidores");
        jBtnRegistroCompetidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegistroCompetidoresActionPerformed(evt);
            }
        });

        jBtnAsignarEquipos.setText("Asignar Equipos");
        jBtnAsignarEquipos.setEnabled(false);
        jBtnAsignarEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAsignarEquiposActionPerformed(evt);
            }
        });

        jBtnReiniciarSimulador.setText("Reiniciar Simulador");
        jBtnReiniciarSimulador.setEnabled(false);
        jBtnReiniciarSimulador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReiniciarSimuladorActionPerformed(evt);
            }
        });

        jBtnCompetencias.setText("Avanzar a las Competencias");
        jBtnCompetencias.setEnabled(false);
        jBtnCompetencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCompetenciasActionPerformed(evt);
            }
        });

        jBtnSalir.setText("Salir");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });

        jCboOrdenamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ordenar", "Ordenar Edad de Menor a Mayor", "Ordenar Edad de Mayor a Menor", "Ordenar ID de Menor a Mayor", "Ordenar ID de Mayor a Menor" }));
        jCboOrdenamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboOrdenamientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jBtnRegistroCompetidores, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jBtnReiniciarSimulador, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jBtnAsignarEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnCompetencias, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jCboOrdenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(364, 364, 364))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(572, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jCboOrdenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnRegistroCompetidores, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnAsignarEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnReiniciarSimulador, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCompetencias, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jBtnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(109, 109, 109)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(196, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRegistroCompetidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegistroCompetidoresActionPerformed
        // TODO add your handling code here:
        inscripcion1.llenar_inscripciones();
        inscripcion1.asignar_ID();
        jTxtRegistroCompetidores.setText(inscripcion1.toString());
        jBtnRegistroCompetidores.setEnabled(false);
        jBtnAsignarEquipos.setEnabled(true);
    }//GEN-LAST:event_jBtnRegistroCompetidoresActionPerformed

    private void jBtnAsignarEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAsignarEquiposActionPerformed
        jTxtEquipos.setText(inscripcion1.imprimir_equipos());
        jBtnAsignarEquipos.setEnabled(false);
        jBtnCompetencias.setEnabled(true);
        jBtnReiniciarSimulador.setEnabled(true);
    }//GEN-LAST:event_jBtnAsignarEquiposActionPerformed

    private void jBtnReiniciarSimuladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReiniciarSimuladorActionPerformed
        jTxtRegistroCompetidores.setText(" ");
        jBtnRegistroCompetidores.setEnabled(true);
        jTxtEquipos.setText(" ");
        jBtnAsignarEquipos.setEnabled(false); 
        jBtnCompetencias.setEnabled(false);
        jCboOrdenamiento.setSelectedIndex(0);
    }//GEN-LAST:event_jBtnReiniciarSimuladorActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_jBtnSalirActionPerformed

    private void jBtnCompetenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCompetenciasActionPerformed
        // TODO add your handling code here:
        jFrmCompetencias ventana1 = new jFrmCompetencias ();
        ventana1.setVisible(true);
        ventana1.setLocationRelativeTo(null);
        this.dispose(); //Para cerrar esta ventana al abrir la siguiente
    }//GEN-LAST:event_jBtnCompetenciasActionPerformed

    private void jCboOrdenamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboOrdenamientoActionPerformed
        if (jCboOrdenamiento.getSelectedIndex() == 1) {
            inscripcion1.ordenar_edad_menor_mayor();
            jTxtRegistroCompetidores.setText(inscripcion1.toString());
        }
        if (jCboOrdenamiento.getSelectedIndex() == 2) {
            inscripcion1.ordenar_edad_mayor_menor();
            jTxtRegistroCompetidores.setText(inscripcion1.toString());
        }
        if (jCboOrdenamiento.getSelectedIndex() == 3) {
            inscripcion1.ordenar_id_menor_mayor();
            jTxtRegistroCompetidores.setText(inscripcion1.toString());
        }
        if (jCboOrdenamiento.getSelectedIndex() == 4) {
            inscripcion1.ordenar_id_mayor_menor();
            jTxtRegistroCompetidores.setText(inscripcion1.toString());
        }
    }//GEN-LAST:event_jCboOrdenamientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAsignarEquipos;
    private javax.swing.JButton jBtnCompetencias;
    private javax.swing.JButton jBtnRegistroCompetidores;
    private javax.swing.JButton jBtnReiniciarSimulador;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JComboBox<String> jCboOrdenamiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTxtEquipos;
    private javax.swing.JTextArea jTxtRegistroCompetidores;
    // End of variables declaration//GEN-END:variables
}
