/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import logica.GeneradorCompetencias;
import static presentacion.ProyectoProgra.competencia; // De esta forma utilizaremos el objeto "competencia" en esta ventana, 
                                                        //que fue creado en la ventana ProyectoProgra


public class jFrmCompetencias extends javax.swing.JFrame {

    int boton;
    boolean boton1 = false, boton2 = false, boton3 = false, boton4 = false, boton5 = false, salir;
    
    public jFrmCompetencias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnPremioGanaderos = new javax.swing.JButton();
        jBtnPremioChuchecas = new javax.swing.JButton();
        jBtnPremioMangos = new javax.swing.JButton();
        jBtnPremioHato = new javax.swing.JButton();
        jBtnPremioPampa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtResultadoCompetencia = new javax.swing.JTextArea();
        jBtnAvanzarResultados = new javax.swing.JButton();
        jBtnReiniciarSimulador = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();
        jBtnGenerarCompetencia = new javax.swing.JButton();
        jLblPremioMangos = new javax.swing.JLabel();
        jLblPemioHato = new javax.swing.JLabel();
        jLblPremioChuchecas = new javax.swing.JLabel();
        jLblPremioGanaderos = new javax.swing.JLabel();
        jLblPremioPampa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnPremioGanaderos.setText("Gran Premio Ganaderos");
        jBtnPremioGanaderos.setToolTipText("Gran Premio Ganaderos (Sede de San Carlos) ");
        jBtnPremioGanaderos.setEnabled(false);
        jBtnPremioGanaderos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPremioGanaderosActionPerformed(evt);
            }
        });

        jBtnPremioChuchecas.setText("Gran Premio Chuchecas");
        jBtnPremioChuchecas.setToolTipText("Gran Premio Chuchecas (Sede de Puntarenas)");
        jBtnPremioChuchecas.setEnabled(false);
        jBtnPremioChuchecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPremioChuchecasActionPerformed(evt);
            }
        });

        jBtnPremioMangos.setText("Gran Premio Mangos");
        jBtnPremioMangos.setToolTipText("Gran Premio Mangos (Sede de Alajuela) ");
        jBtnPremioMangos.setEnabled(false);
        jBtnPremioMangos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPremioMangosActionPerformed(evt);
            }
        });

        jBtnPremioHato.setText("Gran Premio Hato");
        jBtnPremioHato.setToolTipText("Gran Premio Hato (Sede de Atenas) ");
        jBtnPremioHato.setEnabled(false);
        jBtnPremioHato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPremioHatoActionPerformed(evt);
            }
        });

        jBtnPremioPampa.setText("Gran Premio Pampa");
        jBtnPremioPampa.setToolTipText("Gran premio Pampa (Sede de Guanacaste)");
        jBtnPremioPampa.setEnabled(false);
        jBtnPremioPampa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPremioPampaActionPerformed(evt);
            }
        });

        jTxtResultadoCompetencia.setColumns(20);
        jTxtResultadoCompetencia.setRows(5);
        jScrollPane1.setViewportView(jTxtResultadoCompetencia);

        jBtnAvanzarResultados.setText("Avanzar a Resultados");
        jBtnAvanzarResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAvanzarResultadosActionPerformed(evt);
            }
        });

        jBtnReiniciarSimulador.setText("Reiniciar Simulador");
        jBtnReiniciarSimulador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReiniciarSimuladorActionPerformed(evt);
            }
        });

        jBtnSalir.setText("Salir");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });

        jBtnGenerarCompetencia.setText("Generar Competencia");
        jBtnGenerarCompetencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGenerarCompetenciaActionPerformed(evt);
            }
        });

        jLblPremioMangos.setText("NO EMPEZADO");

        jLblPemioHato.setText("NO EMPEZADO");

        jLblPremioChuchecas.setText("NO EMPEZADO");

        jLblPremioGanaderos.setText("NO EMPEZADO");

        jLblPremioPampa.setText("NO EMPEZADO");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("COMPETENCIAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBtnGenerarCompetencia, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jBtnReiniciarSimulador, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jBtnAvanzarResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(380, 380, 380))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLblPremioMangos, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblPemioHato, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblPremioChuchecas, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblPremioGanaderos, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblPremioPampa, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnPremioMangos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnPremioPampa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnPremioHato, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnPremioGanaderos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnPremioChuchecas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnPremioMangos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblPremioMangos))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnPremioHato, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblPemioHato))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnPremioChuchecas, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblPremioChuchecas))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnPremioGanaderos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblPremioGanaderos))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnPremioPampa, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblPremioPampa)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAvanzarResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnReiniciarSimulador, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnGenerarCompetencia, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnPremioMangosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPremioMangosActionPerformed
        competencia.tiempo_competencia1();
        jTxtResultadoCompetencia.setText(competencia.resultados_competencia1()); //"Gran Premio Mangos (Sede de Alajuela)", 
        jLblPremioMangos.setText("FINALIZADO");
        jBtnPremioMangos.setEnabled(false);
    }//GEN-LAST:event_jBtnPremioMangosActionPerformed

    private void jBtnPremioHatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPremioHatoActionPerformed
        competencia.tiempo_competencia2();
        jTxtResultadoCompetencia.setText(competencia.resultados_competencia2()); //"Gran Premio Hato (Sede de Atenas)"
        jLblPemioHato.setText("FINALIZADO");
        jBtnPremioHato.setEnabled(false);
    }//GEN-LAST:event_jBtnPremioHatoActionPerformed

    private void jBtnPremioChuchecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPremioChuchecasActionPerformed
        competencia.tiempo_competencia3();
        jTxtResultadoCompetencia.setText(competencia.resultados_competencia3()); // "Gran Premio Chuchecas (Sede de Puntarenas)"
        jLblPremioChuchecas.setText("FINALIZADO");
        jBtnPremioChuchecas.setEnabled(false);
    }//GEN-LAST:event_jBtnPremioChuchecasActionPerformed

    private void jBtnPremioGanaderosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPremioGanaderosActionPerformed
        competencia.tiempo_competencia4();
        jTxtResultadoCompetencia.setText(competencia.resultados_competencia4()); // "Gran Premio Ganaderos (Sede de San Carlos)"
        jLblPremioGanaderos.setText("FINALIZADO");
        jBtnPremioGanaderos.setEnabled(false);
    }//GEN-LAST:event_jBtnPremioGanaderosActionPerformed

    private void jBtnPremioPampaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPremioPampaActionPerformed
        competencia.tiempo_competencia5();
        jTxtResultadoCompetencia.setText(competencia.resultados_competencia5()); // "Gran Premio Pampa (Sede de Guanacaste)"
        jLblPremioPampa.setText("FINALIZADO");
        jBtnPremioPampa.setEnabled(false);
    }//GEN-LAST:event_jBtnPremioPampaActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnSalirActionPerformed

    private void jBtnReiniciarSimuladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReiniciarSimuladorActionPerformed
        boton1 = false; boton2 = false; boton3 = false; boton4 = false; boton5 = false;
        salir = true; 
        jTxtResultadoCompetencia.setText(" ");
        jLblPremioMangos.setText("NO EMPEZADO");
        jLblPemioHato.setText("NO EMPEZADO");
        jLblPremioChuchecas.setText("NO EMPEZADO");
        jLblPremioGanaderos.setText("NO EMPEZADO");
        jLblPremioPampa.setText("NO EMPEZADO");
        jBtnGenerarCompetencia.setEnabled(true);
    }//GEN-LAST:event_jBtnReiniciarSimuladorActionPerformed

    private void jBtnGenerarCompetenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGenerarCompetenciaActionPerformed
        //El botón "Generar Competencias" se encargará de activar al azar uno de los 5 botones de las competencias
        salir = false;
        do {
            boton = (int) (Math.random() * 5) + 1;
            if (boton == 1 && boton1 == false) {
                jBtnPremioMangos.setEnabled(true);
                jLblPremioMangos.setText("EN CURSO");
                boton1 = true;
                salir = true;
            }
            if (boton == 2 && boton2 == false) {
                jBtnPremioHato.setEnabled(true);
                jLblPemioHato.setText("EN CURSO");
                boton2 = true;
                salir = true;
            }
            if (boton == 3 && boton3 == false) {
                jBtnPremioChuchecas.setEnabled(true);
                jLblPremioChuchecas.setText("EN CURSO");
                boton3 = true;
                salir = true;
            } 
            if (boton == 4 && boton4 == false) {
                jBtnPremioGanaderos.setEnabled(true);
                jLblPremioGanaderos.setText("EN CURSO");
                boton4 = true;
                salir = true;
            }
            if (boton == 5 && boton5 == false) {
                jBtnPremioPampa.setEnabled(true);
                jLblPremioPampa.setText("EN CURSO");
                boton5 = true;
                salir = true;
            }
        } while(salir == false);
        if (boton1 == true && boton2 == true && boton3 == true && boton4 == true && boton5 == true) { //Por medio de esta condicional, cuando los 5 
            jBtnGenerarCompetencia.setEnabled(false);                                                 //botones se hayan utilizado, el boton "Generar Competencia"
        }                                                                                             //se desactivará
            
    }//GEN-LAST:event_jBtnGenerarCompetenciaActionPerformed

    private void jBtnAvanzarResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAvanzarResultadosActionPerformed
        jFrmResultados ventana = new jFrmResultados ();
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(null);
        this.dispose(); //Para cerrar esta ventana al abrir la siguiente
    }//GEN-LAST:event_jBtnAvanzarResultadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrmCompetencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrmCompetencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrmCompetencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrmCompetencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrmCompetencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAvanzarResultados;
    private javax.swing.JButton jBtnGenerarCompetencia;
    private javax.swing.JButton jBtnPremioChuchecas;
    private javax.swing.JButton jBtnPremioGanaderos;
    private javax.swing.JButton jBtnPremioHato;
    private javax.swing.JButton jBtnPremioMangos;
    private javax.swing.JButton jBtnPremioPampa;
    private javax.swing.JButton jBtnReiniciarSimulador;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblPemioHato;
    private javax.swing.JLabel jLblPremioChuchecas;
    private javax.swing.JLabel jLblPremioGanaderos;
    private javax.swing.JLabel jLblPremioMangos;
    private javax.swing.JLabel jLblPremioPampa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxtResultadoCompetencia;
    // End of variables declaration//GEN-END:variables
}
